parameters:
- name: serviceConnectionName
  type: string
- name: infraProvider
  type: string
  default: bicep
  values:
  - bicep
  - tf

jobs:
- job: Build
  pool:
    vmImage: ubuntu-latest
  displayName: Build Bicep and Function App
  variables:
    functionPublishPath: '$(build.artifactstagingdirectory)/functionapp'
    armParametersScriptPath: $(System.DefaultWorkingDirectory)/.pipelines/scripts/Add-ArmParametersFromBicepparamFiles.ps1
    mainBicepPath: $(System.DefaultWorkingDirectory)/.infrastructure/bicep/main.bicep
    functionSolutionPath: $(System.DefaultWorkingDirectory)/function-app/FunctionsOrderFulfillmentDemo.sln
  steps:
    - task: Bash@3
      displayName: Build Infrastructure Templates
      inputs:
        targetType: 'inline'
        script: |
          bicep build $(mainBicepPath)

    - task: PowerShell@2
      displayName: Generate ARM parameters from *.bicepparam
      inputs:
        workingDirectory: $(System.DefaultWorkingDirectory)/.infrastructure/bicep/parameters/
        filePath: $(armParametersScriptPath)

    - task: UseDotNet@2
      displayName: Setup .NET Core SDK
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - script: |
        dotnet restore
        dotnet build $(functionSolutionPath) --configuration Release
      displayName: Build Function App
    
    - task: DotNetCoreCLI@2
      displayName: Publish Function App
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/*.csproj'
        arguments: '--configuration Release --output $(functionPublishPath)'
        modifyOutputPath: false
        zipAfterPublish: true
        workingDirectory: './'

    # - task: MicrosoftSecurityDevOps@1
    #   displayName: 'Microsoft Security DevOps'
    #   inputs:
    #     categories: 'IaC'
    #     tools: 'binskim'
        #config: '$(System.DefaultWorkingDirectory)/.infrastructure/pipelines/templates/secdevops-extension.json'

    - task: PublishPipelineArtifact@1
      displayName: Publish Infrastructure Artifacts
      inputs:
        artifactName: infrastructure
        targetPath: $(System.DefaultWorkingDirectory)/.infrastructure/
    
    - task: PublishPipelineArtifact@1
      displayName: Publish Function App Artifact
      inputs:
        artifactName: functionapp
        targetPath: $(functionPublishPath)
    
    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Scripts
      inputs:
        artifactName: scripts
        targetPath: $(System.DefaultWorkingDirectory)/.pipelines/scripts/
