parameters:
- name: serviceConnectionName
  displayName: Azure DeveOps Service Connection Name
  type: string
  default: 'Christopher House - Internal Demo Sub'

trigger:
  branches:
    include:
     - '*'
pr: none

variables:
  - group: 'sloc-ais-ws'

stages:
 - stage: Build
   displayName: Build Infrastructure and Code
   jobs:
   - template: templates/build.yaml
     parameters:
       serviceConnectionName: $(service-connection-name) # ${{ parameters.serviceConnectionName }}

 - template: 04-Functions/pipelines/templates/deploy.yaml
   parameters:
     serviceConnectionName: $(service-connection-name)
     environmentName: dev
     resourceGroupName: $(dev-resource-group)

 - template: 04-Functions/pipelines/templates/deploy.yaml
   parameters:
     serviceConnectionName: $(service-connection-name)
     environmentName: qa
     resourceGroupName: $(qa-resource-group)
