parameters:
- name: serviceConnectionName
  displayName: Azure DeveOps Service Connection Name
  type: string
  default: 'Christopher House - Internal Demo Sub'

trigger:
  branches:
    include:
     - '*'
pr: none

stages:
 - stage: Build
   displayName: Build Infrastructure and Code
   jobs:
   - template: templates/build.yaml
     parameters:
       serviceConnectionName: ${{ parameters.serviceConnectionName }}

 - template: templates/deploy.yaml
   parameters:
     serviceConnectionName: ${{ parameters.serviceConnectionName }}
     environmentName: dev
     resourceGroupName: APIM-DEMO-RG
     importApimApi: true

 - template: templates/deploy.yaml
   parameters:
     serviceConnectionName: ${{ parameters.serviceConnectionName }}
     environmentName: qa
     resourceGroupName: APIM-DEMO-RG-QA
     importApimApi: false